### PR TITLE
[Merged by Bors] - Authorization overhaul

### PR DESCRIPTION
**Pull request by maltesander**
## Description

- removed authorization module
- switched to `OpaConfig` from operator-rs

closes https://github.com/stackabletech/trino-operator/issues/167

## Review Checklist
- [x] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by fhennig** [comment]
I'll review this

**Comment by fhennig** [comment]
Alright, so the code looks good, I'll test now

**Comment by fhennig** [comment]
The dependency on the secret operator is not documented

**Comment by fhennig** [comment]
The documentation doesn't say how to get to the Web UI

**Review by fhennig — APPROVED** [review]
I've created tickets for the documentation issues as well as the missing test

**Comment by maltesander** [comment]
bors merge

**Pull request closed without merging**
