### PR TITLE
refactor: Change graceful shutdown timeout to string

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Part of https://github.com/stackabletech/trino-operator/pull/461
As discussed in Arc meeting on 2023-08-23

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM!

**Comment by lfrancke** [comment]
This changes the CRD? Do we need anything in the docs, release notes etc.?

**Comment by lfrancke** [comment]
ping @maltesander in the absence of @sbernauer

**Comment by lfrancke** [comment]
Can you link the PR where you fixed the docs?

**Comment by maltesander** [comment]
Sure thing! https://github.com/stackabletech/trino-operator/pull/466

**Pull request merged**
