### PR TITLE
chore: Bump to Hive 4.0.0

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Part of https://github.com/stackabletech/issues/issues/620

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [x] Helm chart can be installed and deployed operator works
- [x] Integration tests passed (for non trivial changes)
- [x] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [x] (Integration-)Test cases added
- [x] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Review by maltesander — DISMISSED** [review]
LGTM!

**Comment by sbernauer** [comment]
Started https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/5/

**Comment by sbernauer** [comment]
Re-running after giving the tests more CPU in https://github.com/stackabletech/ci/commit/f4615ad6a9bad881ef8237f6509471d1df616e3a: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/6/

**Review by maltesander — APPROVED** [review]
LGTM!

**Comment by sbernauer** [comment]
Aaaaaand more CPU: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/7/

**Comment by sbernauer** [comment]
https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/8/

**Comment by sbernauer** [comment]
After doubling the k8s nodes from 5 to 10 tests finally passed :sweat:

**Review by maltesander — APPROVED** [review]
LGTM!

**Pull request merged**
