### PR TITLE
Grant the privileges required for graceful shutdowns to the admin user in the OPA rego rules

### LINKED ISSUE #574: Always provision required Stackable Trino policies e.g. for graceful shutdown
[Relevant Slack discussion](https://stackable-workspace.slack.com/archives/C030VHFLUKZ/p1713510607724659)

We want to provision some policies by Stackable and merge the user-provided ones on top.
This is needed e.g. for graceful shutdown, where the user `admin` needs the permission to initiate a graceful shutdown of workers. If the users does not allow this, graceful shutdown is broken.

We don't want to rely only on documentation ("Please allow this, please allow that" sprinkled all over the documentation), but instead make some assumptions and hard-roll those roles. E.g. we know  that a.) graceful shutdown is always used b.) It's always the user admin issuing the graceful shutdown.

So  the plan is something like
```rego
stackable_default_policies := { "system_information": [{"user": "admin", "allow": ["read", "write"]}], ... }

user_provided_policies := data.trino_policies.policies

policies := stackable_default_policies.union(user_provided_policies)
```

The Stackable default policies can be easily documented. Changes in various places in our code cannot.

If there are problematic edge cases with union  then we can create our own merge function. This wouldn't be too hard because we know exactly how the structure of policies looks like.

```[tasklist]
### Tasks
- [x] https://github.com/stackabletech/trino-operator/pull/573 is updated with what we implemented and merged
- [x] The end-to-end-security is checked for graceful shutdown. It is updated to pull in the new rego rules -> https://github.com/stackabletech/demos/pull/41
```

### PR DESCRIPTION
**Pull request by siegfriedweber**
# Description

Grant the privileges required for graceful shutdowns to the admin user in the OPA rego rules

Required for #574 

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [x] Code contains useful comments
- [ ] Code contains useful logging statements
- [x] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Comment by siegfriedweber** [comment]
:hourglass_flowing_sand: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/119/

**Review by sbernauer — CHANGES_REQUESTED** [review]
The idea and change LGTM. However, I would prefer if we don't slam just every permission on the `admin` user, but would only add the need permissions, `rw` on `system_information` in this case. I know this might make the rules a bit more complicated...

I would be even happier if we would use meanifung names, so not admin but `graceful-shutdown` for graceful shutdown. But I need to check what happens on TrinoClusters without OPA (will they get a 403?)

**Review by sbernauer — APPROVED** [review]
Many thanks

**Comment by sbernauer** [comment]
FYI, I'm copying the new rule to the end-to-end-security demo. I hope they will not be changed before merging

**Pull request merged**
